### PR TITLE
Add OMP walkthrough subparts

### PR DESCRIPTION
**Pull request by noloerino**

### CODE REVIEW

**Comment by paulshaoyuqiao** [comment]
These are some of the things I think might be worth fixing/looking more into:
1. "This make looks familiar", "make" was added by mistake?
2. Can you change xi to alpha_i? This aligns with the course notes (also what we did in problem 3)
3. You are missing the solution (and meta) for part 7.
4. part 5 solution, better to say "shifted versions" than "shifts"
5. It might be a better idea to be more specific with "affect our assumptions" in the question statement for part 5 (like specifically how do we need to modify our original assumption that all our signal vectors must be nearly mutually orthogonal to each other).
6. Might be a better idea to give a graph representing the signals. Also, try wrapping the delays with parentheses (right before part 7)
7. For part 7-10, we might need an actual mechanical example of OMP (like with values on each iteration). The answers are currently good but probably too conceptual (the students could benefit with numerical practice). Can you help work on that? If not, let me know which part I can help with.

**Review by paulshaoyuqiao — CHANGES_REQUESTED** [review]
Can you take a look at the comments on the pull request for potential revisions? Let me know if you need more help with this. Thanks!

**Comment by paulshaoyuqiao** [comment]
@noloerino Feel free to refer to the numerical walkthrough of the OMP example in the course notes for setting up mechanical practice: **page 1 to page 6**
https://inst.eecs.berkeley.edu/~ee16a/fa19/lecture/Note24.pdf

**Comment by paulshaoyuqiao** [comment]
@noloerino This numerical demo might also help as well if you are looking for a simpler and shorter mechanical walkthrough.
https://kore76.files.wordpress.com/2014/10/tutorial_orthogonal_matching_pursuit_mod2.pdf

**Comment by noloerino** [comment]
Will make these changes. Just one thing:
> 2. Can you change xi to alpha_i? This aligns with the course notes (also what we did in problem 3)

Note 24 seems to jump around between using a_i and x_i at different points, and I find a_i to be confusing because it usually refers to the columns of the A matrix. Can you show me where they use alpha?

**Comment by noloerino** [comment]
Fixed and added concrete numbers - I figured the vectors in the notes would be too long/tedious to work through by hand, but the ones in the second link you gave also weren't mutually orthogonal (as the slides they came in used the inner product rather than circcorr to determine closeness) - I ended up fudging my own somewhat mutually orthogonal vectors.

**Pull request merged**
